CREATE SCHEMA IF NOT EXISTS `demodb` ;

CREATE TABLE IF NOT EXISTS `demodb`.`todo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` NVARCHAR(50) NOT NULL,
  `description` NVARCHAR(1000) NULL,
  `priority` INT NOT NULL CHECK (priority > 0 AND priority < 4),
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB